/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RiskIndexRouteImport } from './routes/risk/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as MarketIndexRouteImport } from './routes/market/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as StrategiesCompareRouteImport } from './routes/strategies/compare'
import { Route as StrategiesIdRouteImport } from './routes/strategies/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIndexRoute = RiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesCompareRoute = StrategiesCompareRouteImport.update({
  id: '/strategies/compare',
  path: '/strategies/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIdRoute = StrategiesIdRouteImport.update({
  id: '/strategies/$id',
  path: '/strategies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/alerts/': typeof AlertsIndexRoute
  '/data/': typeof DataIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/market/': typeof MarketIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/risk/': typeof RiskIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/alerts': typeof AlertsIndexRoute
  '/data': typeof DataIndexRoute
  '/logs': typeof LogsIndexRoute
  '/market': typeof MarketIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/risk': typeof RiskIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/compare': typeof StrategiesCompareRoute
  '/alerts/': typeof AlertsIndexRoute
  '/data/': typeof DataIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/market/': typeof MarketIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/risk/': typeof RiskIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/strategies/$id'
    | '/strategies/compare'
    | '/alerts/'
    | '/data/'
    | '/logs/'
    | '/market/'
    | '/portfolio/'
    | '/risk/'
    | '/settings/'
    | '/strategies/'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/strategies/$id'
    | '/strategies/compare'
    | '/alerts'
    | '/data'
    | '/logs'
    | '/market'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/strategies'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/strategies/$id'
    | '/strategies/compare'
    | '/alerts/'
    | '/data/'
    | '/logs/'
    | '/market/'
    | '/portfolio/'
    | '/risk/'
    | '/settings/'
    | '/strategies/'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StrategiesIdRoute: typeof StrategiesIdRoute
  StrategiesCompareRoute: typeof StrategiesCompareRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MarketIndexRoute: typeof MarketIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  RiskIndexRoute: typeof RiskIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/': {
      id: '/risk/'
      path: '/risk'
      fullPath: '/risk/'
      preLoaderRoute: typeof RiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/compare': {
      id: '/strategies/compare'
      path: '/strategies/compare'
      fullPath: '/strategies/compare'
      preLoaderRoute: typeof StrategiesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$id': {
      id: '/strategies/$id'
      path: '/strategies/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof StrategiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StrategiesIdRoute: StrategiesIdRoute,
  StrategiesCompareRoute: StrategiesCompareRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  DataIndexRoute: DataIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MarketIndexRoute: MarketIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  RiskIndexRoute: RiskIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
