/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/strategies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies__get"];
        put?: never;
        /** Create Strategy */
        post: operations["create_strategy_api_strategies__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_strategies__strategy_id__get"];
        /** Update Strategy */
        put: operations["update_strategy_api_strategies__strategy_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Strategy */
        post: operations["start_strategy_api_strategies__strategy_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Strategy */
        post: operations["stop_strategy_api_strategies__strategy_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backtest */
        post: operations["run_backtest_api_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Results */
        get: operations["list_backtest_results_api_backtest_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Result */
        get: operations["get_backtest_result_api_backtest_results__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Summary */
        get: operations["get_portfolio_summary_api_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_api_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trades */
        get: operations["get_trades_api_portfolio_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance */
        get: operations["get_performance_api_portfolio_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-data/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bars */
        get: operations["get_bars_api_market_data_bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-data/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Quotes */
        get: operations["get_latest_quotes_api_market_data_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-data/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Symbols */
        get: operations["list_symbols_api_market_data_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestListItem */
        BacktestListItem: {
            /** Id */
            id: string;
            /** Strategy Id */
            strategy_id: string;
            /** Status */
            status: string;
            metrics: components["schemas"]["BacktestMetrics"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BacktestMetrics */
        BacktestMetrics: {
            /**
             * Sharpe Ratio
             * @default 0
             */
            sharpe_ratio: number;
            /**
             * Sortino Ratio
             * @default 0
             */
            sortino_ratio: number;
            /**
             * Max Drawdown
             * @default 0
             */
            max_drawdown: number;
            /**
             * Win Rate
             * @default 0
             */
            win_rate: number;
            /**
             * Profit Factor
             * @default 0
             */
            profit_factor: number;
            /**
             * Annual Return
             * @default 0
             */
            annual_return: number;
            /**
             * Total Return
             * @default 0
             */
            total_return: number;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /** Strategy Id */
            strategy_id: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Market
             * @default crypto
             */
            market: string;
            /**
             * Symbols
             * @default [
             *       "BTC/USDT"
             *     ]
             */
            symbols: string[];
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Id */
            id: string;
            /** Strategy Id */
            strategy_id: string;
            /**
             * Status
             * @default completed
             */
            status: string;
            /**
             * Equity Curve
             * @default []
             */
            equity_curve: number[];
            /**
             * Trades
             * @default []
             */
            trades: components["schemas"]["BacktestTrade"][];
            /**
             * @default {
             *       "sharpe_ratio": 0,
             *       "sortino_ratio": 0,
             *       "max_drawdown": 0,
             *       "win_rate": 0,
             *       "profit_factor": 0,
             *       "annual_return": 0,
             *       "total_return": 0
             *     }
             */
            metrics: components["schemas"]["BacktestMetrics"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BacktestTrade */
        BacktestTrade: {
            /**
             * Entry Time
             * Format: date-time
             */
            entry_time: string;
            /** Exit Time */
            exit_time?: string | null;
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Entry Price */
            entry_price: number;
            /** Exit Price */
            exit_price?: number | null;
            /** Quantity */
            quantity: number;
            /**
             * Pnl
             * @default 0
             */
            pnl: number;
        };
        /** BarData */
        BarData: {
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Timeframe */
            timeframe: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatestQuote */
        LatestQuote: {
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Price */
            price: number;
            /** Change 24H */
            change_24h: number;
            /** Volume 24H */
            volume_24h: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** PerformanceMetrics */
        PerformanceMetrics: {
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Sortino Ratio */
            sortino_ratio: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Win Rate */
            win_rate: number;
            /** Profit Factor */
            profit_factor: number;
            /** Annual Return */
            annual_return: number;
            /** Total Return */
            total_return: number;
            /** Total Trades */
            total_trades: number;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Total Value */
            total_value: number;
            /** Cash */
            cash: number;
            /** Positions */
            positions: components["schemas"]["PositionItem"][];
            /** Total Pnl */
            total_pnl: number;
            /** Daily Pnl */
            daily_pnl: number;
        };
        /** PositionItem */
        PositionItem: {
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: number;
            /** Entry Price */
            entry_price: number;
            /** Current Price */
            current_price: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
        };
        /** StrategyCreate */
        StrategyCreate: {
            /** Name */
            name: string;
            /** Class Name */
            class_name: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: unknown;
            };
            /** Markets */
            markets: string[];
            /** Timeframes */
            timeframes: string[];
        };
        /** StrategyDetail */
        StrategyDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Class Name */
            class_name: string;
            /** Markets */
            markets: string[];
            /** Timeframes */
            timeframes: string[];
            /**
             * Status
             * @default stopped
             */
            status: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * @default {
             *       "total_return": 0,
             *       "sharpe_ratio": 0,
             *       "max_drawdown": 0,
             *       "win_rate": 0
             *     }
             */
            performance: components["schemas"]["StrategyPerformanceSummary"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** StrategyListItem */
        StrategyListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Class Name */
            class_name: string;
            /** Markets */
            markets: string[];
            /** Timeframes */
            timeframes: string[];
            /**
             * Status
             * @default stopped
             */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StrategyPerformanceSummary */
        StrategyPerformanceSummary: {
            /**
             * Total Return
             * @default 0
             */
            total_return: number;
            /**
             * Sharpe Ratio
             * @default 0
             */
            sharpe_ratio: number;
            /**
             * Max Drawdown
             * @default 0
             */
            max_drawdown: number;
            /**
             * Win Rate
             * @default 0
             */
            win_rate: number;
        };
        /** StrategyUpdate */
        StrategyUpdate: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status?: string | null;
        };
        /** SymbolInfo */
        SymbolInfo: {
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Base */
            base: string;
            /** Quote */
            quote: string;
            /**
             * Status
             * @default active
             */
            status: string;
        };
        /** TradeRecord */
        TradeRecord: {
            /** Id */
            id: string;
            /** Strategy */
            strategy: string;
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Side */
            side: string;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Commission */
            commission: number;
            /** Pnl */
            pnl: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_strategies_api_strategies__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListItem"][];
                };
            };
        };
    };
    create_strategy_api_strategies__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_strategy_api_strategies__strategy_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_strategy_api_strategies__strategy_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_strategy_api_strategies__strategy_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_results_api_backtest_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestListItem"][];
                };
            };
        };
    };
    get_backtest_result_api_backtest_results__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_summary_api_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    get_positions_api_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionItem"][];
                };
            };
        };
    };
    get_trades_api_portfolio_trades_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_api_portfolio_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceMetrics"];
                };
            };
        };
    };
    get_bars_api_market_data_bars_get: {
        parameters: {
            query: {
                /** @description Trading pair symbol */
                symbol: string;
                /** @description Market type */
                market?: string;
                /** @description Bar timeframe */
                timeframe?: string;
                /** @description Start time */
                start?: string | null;
                /** @description End time */
                end?: string | null;
                /** @description Max bars to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarData"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_quotes_api_market_data_latest_get: {
        parameters: {
            query?: {
                /** @description Comma-separated symbols */
                symbols?: string;
                /** @description Market type */
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestQuote"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_symbols_api_market_data_symbols_get: {
        parameters: {
            query?: {
                /** @description Market type */
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
